
on:
  push:
    tags: v[1-9]+.[0-9]+.[0-9]+
    branches: master

jobs:

  tagged-release:
    name: "Tagged Release"
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: "ubuntu-latest"

    steps:
    
      - uses: actions/checkout@v2
      - name: Set up JDK 1.12
        uses: actions/setup-java@v1
        with:
          java-version: 1.12

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: "Release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            ./build/libs/*.jar